spring:
  datasource:
    url:  jdbc:postgresql://dpg-ciojqp6nqqlfegcif4i0-a.oregon-postgres.render.com:5432/database_render_spring_boot_7lce
    username:  database_render_spring_boot_7lce_user
    password: idasWDI8Kll8DxmrMaSws01tP0Lq56kr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    